/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/AboutPage.vue')['default']
    AdminDashboard: typeof import('./components/Admin/AdminDashboard.vue')['default']
    AdminLogin: typeof import('./components/Admin/AdminLogin.vue')['default']
    AiScorePanel: typeof import('./components/AiScorePanel.vue')['default']
    AnalysisList: typeof import('./components/AnalysisList.vue')['default']
    AnalysisV1Display: typeof import('./components/AnalysisV1Display.vue')['default']
    AnchorBindDialog: typeof import('./components/AnchorBindDialog.vue')['default']
    AnchorStatus: typeof import('./components/AnchorStatus.vue')['default']
    AnnouncementBanner: typeof import('./components/AnnouncementBanner.vue')['default']
    ArticleDetail: typeof import('./components/ArticleDetail.vue')['default']
    ArticleKlineChart: typeof import('./components/charts/ArticleKlineChart.vue')['default']
    CompareBucket: typeof import('./components/Compare/CompareBucket.vue')['default']
    CompareView: typeof import('./components/Compare/CompareView.vue')['default']
    ConditionQualityLeaderboard: typeof import('./components/Journal/ConditionQualityLeaderboard.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    EnhancementCards: typeof import('./components/EnhancementCards.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InviteDialog: typeof import('./components/InviteDialog.vue')['default']
    JournalDetailDialog: typeof import('./components/Journal/JournalDetailDialog.vue')['default']
    JournalList: typeof import('./components/Journal/JournalList.vue')['default']
    JournalReviewDialog: typeof import('./components/Journal/JournalReviewDialog.vue')['default']
    JudgmentCard: typeof import('./components/JudgmentCard.vue')['default']
    JudgmentConfirmDialog: typeof import('./components/WyckoffGuide/JudgmentConfirmDialog.vue')['default']
    JudgmentHelp: typeof import('./components/JudgmentHelp.vue')['default']
    JudgmentPreReminder: typeof import('./components/WyckoffGuide/JudgmentPreReminder.vue')['default']
    JudgmentStatusGuide: typeof import('./components/WyckoffGuide/JudgmentStatusGuide.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    MarketOverviewPanel: typeof import('./components/MarketOverviewPanel.vue')['default']
    MarketTimeDisplay: typeof import('./components/MarketTimeDisplay.vue')['default']
    MyJudgments: typeof import('./components/MyJudgments.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    QuotaExceededModal: typeof import('./components/QuotaExceededModal.vue')['default']
    QuotaStatus: typeof import('./components/QuotaStatus.vue')['default']
    RiskFlagExplainer: typeof import('./components/WyckoffGuide/RiskFlagExplainer.vue')['default']
    RiskStockList: typeof import('./components/RiskStockList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButtons: typeof import('./components/ShareButtons.vue')['default']
    StockAnalysisApp: typeof import('./components/StockAnalysisApp.vue')['default']
    StockCard: typeof import('./components/StockCard.vue')['default']
    StockKlineChart: typeof import('./components/charts/StockKlineChart.vue')['default']
    StockSearch: typeof import('./components/StockSearch.vue')['default']
    UserCenterPage: typeof import('./components/UserCenter/UserCenterPage.vue')['default']
    UserOverviewCards: typeof import('./components/UserCenter/UserOverviewCards.vue')['default']
    ValueLoop: typeof import('./components/ValueLoop.vue')['default']
    WatchlistFilters: typeof import('./components/Watchlist/WatchlistFilters.vue')['default']
    WatchlistItemCard: typeof import('./components/Watchlist/WatchlistItemCard.vue')['default']
    WatchlistList: typeof import('./components/Watchlist/WatchlistList.vue')['default']
  }
}
